version: "2.30"

services:
  airport:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate && 
              python manage.py init_superuser &&
              python manage.py loaddata data.json &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
      - media:/media
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:$PGDATA

volumes:
  db_data:
  media:
